<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sch</string>
	</array>
	<key>name</key>
	<string>Rage Scripting Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#primitives</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(INT|BOOL|FLOAT|CONST_INT)\b</string>
			<key>name</key>
			<string>storage.type.ragescriptinglanguage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(NATIVE)\b</string>
			<key>name</key>
			<string>storage.keyword.ragescriptinglanguage</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(FUNC|PROC)\s+([a-zA-Z_][a-zA-Z0-9_]*\s+)?([a-zA-Z_][a-zA-Z0-9_]*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.keyword.ragescriptinglanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.ragescriptinglanguage</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ragescriptinglanguage</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#primitives</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([a-zA-Z_][a-zA-Z0-9_]*(?:\s*&amp;\s*|\s+))([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.ragescriptinglanguage</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.ragescriptinglanguage</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ragescriptinglanguage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.ragescriptinglanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ENUM|STRICT_ENUM|STRUCT)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ENDENUM|ENDSTRUCT|USING)\b</string>
			<key>name</key>
			<string>keyword.control.ragescriptinglanguage</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ragescriptinglanguage</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.ragescriptinglanguage</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>primitives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.ragescriptinglanguage punctuation.definition.string.begin.ragescriptinglanguage</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.ragescriptinglanguage punctuation.definition.string.end.ragescriptinglanguage</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.ragescriptinglanguage</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w\d.])\d+(\.\d+)?</string>
					<key>name</key>
					<string>constant.numeric.ragescriptinglanguage</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TRUE|FALSE|NULL)\b</string>
					<key>name</key>
					<string>constant.language.ragescriptinglanguage</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|-|%|==?</string>
					<key>name</key>
					<string>keyword.operator.ragescriptinglanguage</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ragescriptinglanguage</string>
	<key>uuid</key>
	<string>996B4CB9-6ACA-4258-B912-00A9B5DF464A</string>
</dict>
</plist>
